GameStore/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ChiTietDonHang1 = new HashSet<ChiTietDonHang>();
            this.ChiTietGioHang = new HashSet<ChiTietGioHang>();
            this.HinhAnh = new HashSet<HinhAnh>();
        }
    
        public int maSP { get; set; }
        public string tenSP { get; set; }
        public double giaTien { get; set; }
        public string chitietSP { get; set; }
        public int maDM { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string hinhAnh1 { get; set; }
        public string hinhAnh2 { get; set; }
        public string hinhAnh3 { get; set; }
        public string hinhAnh4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHang { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnh { get; set; }
    }
}

GameStore/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameStore.Models;

namespace GameStore.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        private GameStoreEntities db = new GameStoreEntities();

        // GET: Admin/SanPham
        public ActionResult Index()
        {
            var sanPham = db.SanPham.Include(s => s.DanhMuc);
            return View(sanPham.ToList());
        }

        // GET: Admin/SanPham/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: Admin/SanPham/Create
        public ActionResult Create()
        {
            ViewBag.maDM = new SelectList(db.DanhMuc, "maDM", "tenDM");
            return View();
        }

        // POST: Admin/SanPham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maSP,tenSP,giaTien,chitietSP,maDM,soLuong,hinhAnh1,hinhAnh2,hinhAnh3,hinhAnh4")] SanPham sanPham,
            HttpPostedFileBase hinh1, HttpPostedFileBase hinh2, HttpPostedFileBase hinh3, HttpPostedFileBase hinh4)
        {

            if (ModelState.IsValid)
            {

                var idImage = Guid.NewGuid().ToString();
                var idImage2 = Guid.NewGuid().ToString();
                var idImage3 = Guid.NewGuid().ToString();
                var idImage4 = Guid.NewGuid().ToString();
                string _FileName = "";
                string _FileName2 = "";
                string _FileName3 = "";
                string _FileName4 = "";

                int index = hinh1.FileName.IndexOf('.');
                int index2= hinh2.FileName.IndexOf('.');
                int index3 = hinh3.FileName.IndexOf('.');
                int index4 = hinh4.FileName.IndexOf('.');
              
                _FileName = idImage.ToString() + "." + hinh1.FileName.Substring(index + 1);
                _FileName2 = idImage2.ToString() + "." + hinh2.FileName.Substring(index2 + 1);
                _FileName3 = idImage3.ToString() + "." + hinh3.FileName.Substring(index3 + 1);
                _FileName4 = idImage4.ToString() + "." + hinh4.FileName.Substring(index4 + 1);

                string path1 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName);
                string path2 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName2);
                string path3 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName3);
                string path4 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName4);

                hinh1.SaveAs(path1);
                hinh2.SaveAs(path2);
                hinh3.SaveAs(path3);
                hinh3.SaveAs(path4);

                 sanPham.hinhAnh1 =  _FileName;
                 sanPham.hinhAnh2 =   _FileName2;                            
                 sanPham.hinhAnh3 =   _FileName3;
                 sanPham.hinhAnh4 =   _FileName4;
                

                db.SanPham.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.maDM = new SelectList(db.DanhMuc, "maDM", "tenDM", sanPham.maDM);
            return View(sanPham);
        }

        // GET: Admin/SanPham/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.maDM = new SelectList(db.DanhMuc, "maDM", "tenDM", sanPham.maDM);
            return View(sanPham);
        }

        // POST: Admin/SanPham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maSP,tenSP,giaTien,chitietSP,maDM,soLuong,hinhAnh1,hinhAnh2,hinhAnh3,hinhAnh4")] SanPham sanPham,
            HttpPostedFileBase hinh1, HttpPostedFileBase hinh2, HttpPostedFileBase hinh3, HttpPostedFileBase hinh4)
        {
            if (ModelState.IsValid)
            {
                var idImage = Guid.NewGuid().ToString();
                var idImage2 = Guid.NewGuid().ToString();
                var idImage3 = Guid.NewGuid().ToString();
                var idImage4 = Guid.NewGuid().ToString();
                string _FileName = "";
                string _FileName2 = "";
                string _FileName3 = "";
                string _FileName4 = "";

                int index = hinh1.FileName.IndexOf('.');
                int index2 = hinh2.FileName.IndexOf('.');
                int index3 = hinh3.FileName.IndexOf('.');
                int index4 = hinh4.FileName.IndexOf('.');

                _FileName = idImage.ToString() + "." + hinh1.FileName.Substring(index + 1);
                _FileName2 = idImage2.ToString() + "." + hinh2.FileName.Substring(index2 + 1);
                _FileName3 = idImage3.ToString() + "." + hinh3.FileName.Substring(index3 + 1);
                _FileName4 = idImage4.ToString() + "." + hinh4.FileName.Substring(index4 + 1);

                string path1 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName);
                string path2 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName2);
                string path3 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName3);
                string path4 = Path.Combine(Server.MapPath("~/UploadFile"), _FileName4);

                hinh1.SaveAs(path1);
                hinh2.SaveAs(path2);
                hinh3.SaveAs(path3);
                hinh4.SaveAs(path4);

                sanPham.hinhAnh1 =  _FileName;
                sanPham.hinhAnh2 =   _FileName2;
                sanPham.hinhAnh3 =   _FileName3;
                sanPham.hinhAnh4 =  _FileName4;
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.maDM = new SelectList(db.DanhMuc, "maDM", "tenDM", sanPham.maDM);
            return View(sanPham);
        }

        // GET: Admin/SanPham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/SanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPham.Find(id);
            db.SanPham.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameStore/Areas/Admin/Views/SanPham/Create.cshtml
@model GameStore.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/layoutAdmin.cshtml";
}

<h2>Thêm sản phẩm</h2>

@using (Html.BeginForm("Create", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.tenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chitietSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chitietSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.chitietSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maDM, "maDM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("maDM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.maDM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 1</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg" required name="hinh1" type="file" } />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 2</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg" required name="hinh2" type="file" } />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 3</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg" required name="hinh3" type="file" } />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 4</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg" required name="hinh4" type="file" } />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GameStore/Areas/Admin/Views/SanPham/Delete.cshtml
@model GameStore.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/layoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chitietSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chitietSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhAnh1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhAnh2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhAnh3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhAnh4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.tenDM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.tenDM)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GameStore/Areas/Admin/Views/SanPham/Details.cshtml
@model GameStore.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/layoutAdmin.cshtml";
}
<style>
    img{
     
        height:300px;
    }
</style>
<h2>Chi tiết sản phẩm</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tenSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chitietSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chitietSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh1)
        </dt>

        <dd>
            <img src="~/UploadFile/@Model.hinhAnh1" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh2)
        </dt>

        <dd>
            <img src="~/UploadFile/@Model.hinhAnh2" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh3)
        </dt>

        <dd>
            <img src="~/UploadFile/@Model.hinhAnh3" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhAnh4)
        </dt>

        <dd>
            <img src="~/UploadFile/@Model.hinhAnh4" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.tenDM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.tenDM)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.maSP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GameStore/Areas/Admin/Views/SanPham/Edit.cshtml
@model GameStore.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/layoutAdmin.cshtml";
}

<h2>Chỉnh sửa sản phẩm</h2>
@using (Html.BeginForm("Edit", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.maSP)

        <div class="form-group">
            @Html.LabelFor(model => model.tenSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.chitietSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chitietSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.chitietSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maDM, "maDM", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("maDM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.maDM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 1</label>
            <div class="col-md-10">
                <input class="form-control" value="~/UploadFile/@Model.hinhAnh1" accept="image/png, image/gif, image/jpeg"  name="hinh1" type="file" } />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 2</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg"  name="hinh2" type="file" } />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 3</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg"  name="hinh3" type="file" } />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Hình ảnh 4</label>
            <div class="col-md-10">
                <input class="form-control" accept="image/png, image/gif, image/jpeg"  name="hinh4" type="file" } />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GameStore/Areas/Admin/Views/SanPham/Index.cshtml
@model IEnumerable<GameStore.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/layoutAdmin.cshtml";
}

<h2>Danh sách sản phẩm</h2>

<p>
    @Html.ActionLink("Thêm sản phẩm", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.hinhAnh1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tenSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.giaTien)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.soLuong)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.DanhMuc.tenDM)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {


<tr>
    <td>
        @if (item.hinhAnh1 != null) {
        <img style="width:100px;" src="~/UploadFile/@item.hinhAnh1" />
        }

    </td>
    <td>
        <div style="width:100px;">  @item.tenSP</div>
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.giaTien)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.soLuong)
    </td>


    <td>
        @Html.DisplayFor(modelItem => item.DanhMuc.tenDM)
    </td>
    <td>
        @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.maSP }) |
        @Html.ActionLink("Xem chi tiết", "Details", new { id = item.maSP })|
        @Html.ActionLink("Xóa SP", "Delete", new { id = item.maSP })


    </td>
</tr>
    }

</table>
@Scripts.Render("~/bundles/admin/jquery")

<script>
        
    $('.sp').addClass('active');
    </script>